---

version: "3.8"

services:
  initialize-sandbox:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    command:
      - |
        echo '{ "genesis_pubkey": "edpkuSLWfVU1Vq7Jg9FucPyKmma6otcMHac9zG4oU1KMHSTBpJuGQ2" }' > /home/tezos/sandbox.json
    volumes:
      - shared-data:/home/tezos

  tezedge-node:
    image: ${TEZEDGE_IMAGE:-tezedge/tezedge:latest}
    command: ["--network=sandbox", "--sandbox-patch-context-json-file=/tmp/shared/sandbox.json", "--p2p-port=9732", "--rpc-port=8732", "--log=terminal", "--log-level=trace", "--tezos-context-storage=irmin", "--peer-thresh-low=0", "--peer-thresh-high=10", "--identity-expected-pow=0.0"]
    volumes:
      - shared-data:/tmp/shared
      - tezedge-data:/tmp/tezos


  octez-node:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    command:
      - |
        tezos-node config init --network sandbox --net-addr 0.0.0.0:9732 --rpc-addr 0.0.0.0:8732 --allow-all-rpc=0.0.0.0:8732 --expected-pow 0.0 && tezos-node identity generate || true
        tezos-node run --sandbox /home/tezos/sandbox.json --no-bootstrap-peers --singleprocess --synchronisation-threshold 0 -vv --connections 10
    ports:
      - 8732:8732
    environment:
      - TEZOS_NODE_DIR=/home/tezos/tezos-node-sandbox
    volumes:
      - shared-data:/home/tezos

  node-1:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    command:
      - |
        tezos-node config init --network sandbox --net-addr 0.0.0.0:9732 --rpc-addr 0.0.0.0:8732 --allow-all-rpc=0.0.0.0:8732 --expected-pow 0.0 && tezos-node identity generate || true
        tezos-node run --sandbox /home/tezos/sandbox.json --no-bootstrap-peers --singleprocess --synchronisation-threshold 0 -vv --connections 1
    environment:
      - TEZOS_NODE_DIR=/home/tezos/node-1
    volumes:
      - shared-data:/home/tezos

  node-2:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    command:
      - |
        tezos-node config init --network sandbox --net-addr 0.0.0.0:9732 --rpc-addr 0.0.0.0:8732 --allow-all-rpc=0.0.0.0:8732 --expected-pow 0.0 && tezos-node identity generate || true
        tezos-node run --sandbox /home/tezos/sandbox.json --no-bootstrap-peers --singleprocess --synchronisation-threshold 0 -vv --connections 1
    environment:
      - TEZOS_NODE_DIR=/home/tezos/node-2
    volumes:
      - shared-data:/home/tezos


  curl:
    image: cfmanteiga/alpine-bash-curl-jq
    command: curl -s http://${NODE:-}:8732${URL-}

  initialize-protocol:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    environment:
      - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=YES
      - NODE=${NODE:-}
    command:
      - |
        alias tezos-client="tezos-client -E http://$$NODE:8732"
        tezos-client import secret key activator unencrypted:edsk31vznjHSSpGExDMHYASz45VZqXN4DPxvsa4hAyY8dHM28cZzp6
        tezos-client activate protocol PtHangz2aRngywmSRGGvrcTyMbbdpWdpFKuS4uMWxg2RaH9i1qx with fitness 1 and key activator and parameters /home/tezos/parameters.json
    volumes:
      - shared-data:/home/tezos

  connect-nodes:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    environment:
      - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=YES
      - NODE=${NODE:-}
      - ADDRS=${ADDRS:-}
    command:
      - |
        alias tezos-admin-client="tezos-admin-client -E http://$$NODE:8732"
        for address in $$ADDRS; do tezos-admin-client connect address $$address:9732; done

  gen-keys:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    environment:
      - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=YES
      - NODE=${NODE:-}
      - ACCS=${ACCS:-}
    command:
      - |
        alias tezos-client="tezos-client -E http://$$NODE:8732"
        for acc in $$ACCS; do tezos-client gen keys $$acc; done
    volumes:
      - shared-data:/home/tezos

  gen-parameters:
    image: cfmanteiga/alpine-bash-curl-jq
    entrypoint: ["sh", "-ex", "-c"]
    command:
      - |
        bootstrap_accounts=$$(jq '[ .[] | [ (.value | sub("unencrypted:"; "")), "4000000000000" ] ]' /home/tezos/.tezos-client/public_keys)
        cat > /home/tezos/parameters.json <<EOF
        {
          "bootstrap_accounts": $$bootstrap_accounts,
          "preserved_cycles": 2, "blocks_per_cycle": 8, "blocks_per_commitment": 4,
          "blocks_per_roll_snapshot": 4, "blocks_per_voting_period": 64,
          "time_between_blocks": [ "1", "1" ], "endorsers_per_block": 256,
          "hard_gas_limit_per_operation": "1040000",
          "hard_gas_limit_per_block": "5200000", "proof_of_work_threshold": "-1",
          "tokens_per_roll": "8000000000",
          "seed_nonce_revelation_tip": "125000", "origination_size": 257,
          "block_security_deposit": "640000000",
          "endorsement_security_deposit": "2500000",
          "baking_reward_per_endorsement": [ "78125", "11719" ],
          "endorsement_reward": [ "78125", "52083" ], "cost_per_byte": "250",
          "hard_storage_limit_per_operation": "60000", "quorum_min": 2000,
          "quorum_max": 7000, "min_proposal_quorum": 500, "initial_endorsers": 1,
          "delay_per_missing_endorsement": "1", "minimal_block_delay": "1",
          "liquidity_baking_subsidy": "2500000",
          "liquidity_baking_sunset_level": 4096,
          "liquidity_baking_escape_ema_threshold": 1000000
        }
        EOF
    volumes:
      - shared-data:/home/tezos

  endorser:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    environment:
      - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=YES
      - NODE=${NODE:-}
    command:
      - |
        tezos-endorser-011-PtHangz2 --log-requests -E http://$$NODE:8732 run acc3
    volumes:
      - shared-data:/home/tezos

  baker-1:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    environment:
      - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=YES
      - TEZOS_NODE_DIR=/home/tezos/node-1
    command:
      - |
        alias tezos-client="tezos-client -E http://node-1:8732"
        tezos-client bake for acc1 --context $${TEZOS_NODE_DIR}/context
    volumes:
      - shared-data:/home/tezos

  baker-2:
    image: tezos/tezos:v11-release
    entrypoint: ["sh", "-ex", "-c"]
    environment:
      - TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER=YES
      - TEZOS_NODE_DIR=/home/tezos/node-2
    command:
      - |
        alias tezos-client="tezos-client -E http://node-2:8732"
        tezos-client bake for acc2 --context $${TEZOS_NODE_DIR}/context
    volumes:
      - shared-data:/home/tezos


volumes:
  shared-data:
  tezedge-data:
